name: 'check aur package update'
branding:
  icon: user-check
  color: gray-dark
inputs:
  aur-git:
    required: true
  ur-repo:
    required: true
  branch:
    required: false
  path:
    required: false
  github-token:
    required: true
  

runs:
  using: "composite"
  steps:
    - name: clone aur-git
      run: git clone ${{inputs.aur-git}} aur-git

    - name: get last built commit
      run: |
        cd aur-git
        URL="https://api.github.com/repos/${{inputs.ur-repo}}/contents/"

        if [ ! "${{inputs.path}}" -e "" ]; then
          URL="${URL}${{inputs.path}}/"
        fi

        URL="${URL}/built_commit"
        if [ ! "${{inputs.branch}}" -e "" ]; then
          URL="${URL}?ref=${{inputs.branch}}"
        fi

        BUILT_COMMIT=$(curl $URL -H "Authorization: token ${{inputs.github-token}}")
        if [ ! "$BUILT_COMMIT" -e "$(git rev-parse HEAD)" ]; then
          touch ../needUpdating
        fi
