name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - id: check_update
      uses: highFreqSurfer/check-aur-package-update@main
      with:
        aur-git: linux-cachyos
        ur-repo: highFreqSurfer/test-action
        branch: package
    
    - name: print steps
      run: |
        echo "Step outputs: ${{ toJSON(steps) }}"
